const form=document.getElementById('order-form'),checkout=document.getElementById('order');
let selected=0,counts=flavors.map(()=>0),cart=[],checkoutTrigger=null;
const money=n=>`${n.toFixed(2).replace('.00','')} ريال`;
const pack=()=>packages[selected];
const count=()=>counts.reduce((a,b)=>a+b,0);
function localDate(){const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;}form.elements.date.min=localDate();
const builder=document.getElementById('box-builder');
builder.innerHTML=`<fieldset class="box-options"><legend>1. اختر البوكس</legend>${packages.map((p,i)=>`<label class="box-option"><input type="radio" name="package" value="${i}" ${i===0?'checked':''}><span>${p.name}<small>من ${money(p.count*(p.size==='small'?3:7))} حسب النكهات</small></span></label>`).join('')}</fieldset><div class="builder-heading"><h3>2. وزّع الحبات على النكهات</h3><span id="box-progress" aria-live="polite"></span></div>`;
function renderProducts(){document.getElementById('products').innerHTML=flavors.map((f,i)=>`<article class="product-card"><img class="flavor-image" src="assets/flavors/${f.id}.png" alt="سينابون بنكهة ${f.name}" loading="lazy"><div class="product-content"><h3>${f.name}</h3><p>${f.description}</p><strong class="piece-price">${money(piecePrice(f,pack().size))} <small>للحبة ${pack().size==='small'?'الصغيرة':'الكبيرة'}</small></strong><button type="button" class="fill-box" data-fill="${i}">أكمل البوكس بهذه النكهة</button><div class="quantity"><span>عدد الحبات</span><div class="counter"><button type="button" data-flavor="${i}" data-delta="-1" aria-label="تقليل ${f.name}">−</button><input type="number" min="0" max="${pack().count}" value="${counts[i]}" data-count="${i}" aria-label="عدد حبات ${f.name}"><button type="button" data-flavor="${i}" data-delta="1" aria-label="زيادة ${f.name}">+</button></div></div></div></article>`).join('');updateBuilder();}
function updateBuilder(){const used=count(),remaining=pack().count-used;document.getElementById('box-progress').textContent=`${used} / ${pack().count} حبة`;document.getElementById('box-price').textContent=money(boxPrice(pack(),counts));document.getElementById('builder-status').textContent=remaining?`متبقي ${remaining} حبة لإكمال البوكس`:'البوكس مكتمل، جاهز للإضافة للسلة';document.getElementById('add-box').disabled=remaining!==0;document.querySelectorAll('[data-count]').forEach(input=>input.value=counts[Number(input.dataset.count)]);document.querySelectorAll('[data-flavor]').forEach(button=>button.disabled=Number(button.dataset.delta)>0?remaining===0:counts[Number(button.dataset.flavor)]===0);}
builder.addEventListener('change',e=>{if(e.target.name!=='package')return;selected=Number(e.target.value);counts=flavors.map(()=>0);renderProducts();});
document.getElementById('products').addEventListener('click',e=>{const fill=e.target.closest('[data-fill]');if(fill){counts[Number(fill.dataset.fill)]+=pack().count-count();updateBuilder();return;}const b=e.target.closest('[data-flavor]');if(!b)return;const i=Number(b.dataset.flavor),delta=Number(b.dataset.delta);counts[i]=Math.max(0,Math.min(pack().count-count()+counts[i],counts[i]+delta));updateBuilder();});
document.getElementById('products').addEventListener('input',e=>{if(!e.target.matches('[data-count]'))return;const i=Number(e.target.dataset.count);counts[i]=Math.max(0,Math.min(pack().count-count()+counts[i],Math.trunc(Number(e.target.value)||0)));updateBuilder();});
document.getElementById('add-box').addEventListener('click',()=>{if(count()!==pack().count)return;cart.push({package:selected,counts:[...counts],quantity:1});counts=flavors.map(()=>0);updateBuilder();refresh();document.getElementById('builder-status').textContent='أُضيف البوكس للسلة. أكمل الطلب أو جهّز بوكسًا آخر.';});
function totals(){return cart.reduce((t,line)=>{t.boxes+=line.quantity;t.pieces+=packages[line.package].count*line.quantity;t.price+=boxPrice(packages[line.package],line.counts)*line.quantity;return t;},{boxes:0,pieces:0,price:0});}
function message(){const d=new FormData(form),t=totals();return ['مرحبًا Dana Sweets، أرغب في الطلب:',...cart.flatMap((line,i)=>{const p=packages[line.package];return [`\nبوكس ${i+1}: ${p.name} × ${line.quantity}`, ...flavors.flatMap((f,j)=>line.counts[j]?[`• ${f.name}: ${line.counts[j]} حبة في البوكس × ${money(piecePrice(f,p.size))} للحبة`]:[]),`سعر البوكس: ${money(boxPrice(p,line.counts))} | مجموع السطر: ${money(boxPrice(p,line.counts)*line.quantity)}`];}),`\nإجمالي البوكسات: ${t.boxes}`,`إجمالي الحبات: ${t.pieces}`,`إجمالي المنتجات: ${money(t.price)} (دون التوصيل)`,`الاسم: ${String(d.get('customer')||'').trim()||'—'}`,`رقم الجوال: ${String(d.get('mobile')||'').trim()||'—'}`,`العنوان في جدة: ${String(d.get('address')||'').trim()||'—'}`,`التاريخ المطلوب: ${d.get('date')||'—'}`,...(String(d.get('notes')||'').trim()?[`ملاحظات: ${String(d.get('notes')).trim()}`]:[]),'أرجو تأكيد التوفر وموعد ورسوم التوصيل. شكرًا!'].join('\n');}
function refresh(){const t=totals();document.getElementById('cart-count').textContent=t.boxes;document.getElementById('cart-label').textContent=t.boxes?`السلة · ${money(t.price)}`:'جهّز بوكسك';document.getElementById('order-items').innerHTML=cart.length?cart.map((line,i)=>{const p=packages[line.package];return `<div class="cart-box"><strong>${p.name}</strong><p>${flavors.flatMap((f,j)=>line.counts[j]?[`${f.name} ${line.counts[j]}`]:[]).join(' · ')}</p><p>سعر البوكس: ${money(boxPrice(p,line.counts))}</p><div class="checkout-item"><div class="counter"><button type="button" data-cart="${i}" data-delta="-1" aria-label="تقليل عدد البوكسات">−</button><span>${line.quantity}</span><button type="button" data-cart="${i}" data-delta="1" aria-label="زيادة عدد البوكسات">+</button></div><strong>${money(boxPrice(p,line.counts)*line.quantity)}</strong><button type="button" class="remove-box" data-remove="${i}">حذف</button></div></div>`;}).join('')+`<strong>الإجمالي: ${money(t.price)}</strong><p>${t.boxes} بوكس · ${t.pieces} حبة · دون رسوم التوصيل</p>`:'السلة فارغة. جهّز بوكسًا وأضفه من قائمة النكهات.';document.getElementById('message-preview').textContent=message();}
document.getElementById('order-items').addEventListener('click',e=>{const remove=e.target.closest('[data-remove]'),b=e.target.closest('[data-cart]');if(remove)cart.splice(Number(remove.dataset.remove),1);else if(b){const i=Number(b.dataset.cart);cart[i].quantity=Math.min(99,cart[i].quantity+Number(b.dataset.delta));if(cart[i].quantity===0)cart.splice(i,1);}else return;refresh();});
function closeCheckout(){if(checkout.open)checkout.close();document.body.classList.remove('checkout-open');if(checkoutTrigger)checkoutTrigger.focus({preventScroll:true});}
function openCheckout(e){if(e)e.preventDefault();if(!cart.length){document.getElementById('flavors').scrollIntoView({behavior:'smooth'});return;}checkoutTrigger=e?.currentTarget||document.querySelector('.sticky-order');refresh();if(!checkout.open)checkout.showModal();document.body.classList.add('checkout-open');}
document.querySelectorAll('a[href="#order"]').forEach(link=>link.addEventListener('click',openCheckout));document.querySelector('.checkout-close').addEventListener('click',closeCheckout);checkout.addEventListener('close',()=>document.body.classList.remove('checkout-open'));
checkout.addEventListener('click',e=>{if(e.target!==checkout)return;const r=checkout.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeCheckout();});form.addEventListener('input',()=>document.getElementById('message-preview').textContent=message());
form.addEventListener('submit',e=>{e.preventDefault();if(!cart.length){document.getElementById('form-status').textContent='أضف بوكسًا واحدًا على الأقل للسلة.';return;}if(!form.elements.customer.value.trim()||form.elements.address.value.trim().length<8){document.getElementById('form-status').textContent='يرجى كتابة الاسم وعنوان واضح.';return;}form.elements.date.min=localDate();if(!form.checkValidity()){form.reportValidity();return;}window.open(`https://wa.me/966507448979?text=${encodeURIComponent(message())}`,'_blank','noopener,noreferrer');});renderProducts();refresh();
